# this file contains examples of R scripts to put various data together from the 
# artocarpus databases

# set your working directory. if you're on windows, you use '\\' between directories, 
# eg setwd("c:\\\\data\\")
setwd("/home/josh/source/artocarpus_data")

# exported from collection table. exports include a date-time stamp.
# collection$ID is the main record identifier
# other identifiers are herbAccession or herbCollection (FIXME!)
collection <- read.csv("collectiondata_results_2013_01_22_12_05_58.csv")

# exported from extractions. extractionID is autogenerated. 
# fk_extractions_collection_ID refers to collection$ID.
extractions <- read.csv("extractions_results_2013_01_22_12_06_12.csv")

# from sequences. sequenceID is autogenerated. fk_sequences_extractions_ID refers
# to extractions$extractionID
sequences <- read.csv("sequences_results_2013_01_22_12_06_23.csv")

# the relevant functions you want are in the merge() family. see ?merge for more
# information, and http://en.wikipedia.org/wiki/Join_%28SQL%29 for too much info.
# in general, you probably won't need to do anything beyond inner joins, which is
# the default method for merge(). you'll need to set by.x and by.y, since they're
# always named differently (and natural joins are unsafe anyway). if you're more 
# comfortable with SQL, check out the sqldf package.

# column headings for child tables are labeled with "fk". the convention is:
# fk_childtablename_parenttablename_ID
# the key that links the extractions table to collections is as follows:
# fk_extractions_collection_ID

#merge sequence data with extraction data
m.sequences_extractions <- merge(sequences, extractions, 
											 by.x="fk_sequences_extractions_ID",
											 by.y="extractionID"
											)

#now merge in the collection data
m.collection_sequences <- merge(collection, m.sequences_extractions,
										  by.x="ID",
										  by.y="fk_extractions_collection_ID"
										  )

# from here you can export the CSV file or reorder the columns if you really wanted.
# now would be a good time to rename them or drop them before exporting.

attach(m.collection_sequences) #attach is ugly, i generally avoid it, but it's fine for this
trimmed <- data.frame(vectors, from, the, m.collection_sequences, dataframe)
detach(m.collection_sequences) #detach ASAP

write.csv(trimmed, file="output.csv") #call it what you like, it ends up in your wd from above