#this file contains examples of R scripts to put various data together from the 
#artocarpus databases

#set your working directory. i have picked a directory that is not part of the 
#git repository.
setwd("/home/josh/source/artocarpus_private")

#exported from collection table. collection$ID is the main record identifier
collection <- read.csv("collectiondata_results_2013_01_22_12_05_58.csv")

#exported from extractions. extractionID is autogenerated. fk_extractions_collection_ID
#refers to collection$ID.
extractions <- read.csv("extractions_results_2013_01_22_12_06_12.csv")

#from sequences. sequenceID is autogenerated. fk_sequences_extractions_ID refers to
#collection$ID
sequences <- read.csv("sequences_results_2013_01_22_12_06_23.csv")
