# this file contains examples of R scripts to put various data together from the 
# artocarpus databases

# set your working directory. if you're on windows, you use '\\' between directories, 
# eg setwd("c:\\\\data\\")
setwd("/home/josh/source/artocarpus_data")

# exported from collection table. exports include a date-time stamp.
# collection$ID is the main record identifier
# other identifiers are herbAccession or herbCollection (FIXME!)
collection <- read.csv("collectiondata_results_2013_01_22_12_05_58.csv")

# exported from extractions. extractionID is autogenerated. 
# fk_extractions_collection_ID refers to collection$ID.
extractions <- read.csv("extractions_results_2013_01_22_12_06_12.csv")

# from sequences. sequenceID is autogenerated. fk_sequences_extractions_ID refers
# to extractions$extractionID
sequences <- read.csv("sequences_results_2013_01_22_12_06_23.csv")

# the relevant functions you want are in the merge() family. see ?merge for more
# information, and http://en.wikipedia.org/wiki/Join_%28SQL%29 for too much info.
# in general, you probably won't need to do anything beyond inner joins, which is
# the default method for merge(). you'll need to set by.x and by.y, since they're
# always named differently (and natural joins are unsafe anyway). if you're more 
# comfortable with SQL, check out the sqldf package.

# column headings for child tables are labeled with "fk". the convention is:
# fk_childtablename_parenttablename_ID
# the key that links the extractions table to collections is as follows:
# fk_extractions_collection_ID

#merge sequence data with extraction data
m.sequences_extractions <- merge(sequences, extractions, 
											 by.x="fk_sequences_extractions_ID",
											 by.y="extractionID"
											)

#now merge in the collection data
m.collection_sequences <- merge(collection, m.sequences_extractions,
										  by.x="ID",
										  by.y="fk_extractions_collection_ID"
										  )

# you can add in additional data from tables using the same method, or cut
# down the dataframes as appropriate for your use. you could write out FASTA
# files too. SeqinR, biomaRt, and Biostrings all have fasta functions. this way,
# you could concatenate the fields you want for the sequence header and output
# useful FASTA files easier than trying to do it through the Xataface software. 